# Project: CITM_a0.8.4_rc1
# Makefile created by Red Panda C++ 3.4.3279

CXX      = "g++.exe"
CC       = "gcc.exe"
WINDRES  = "windres.exe"
RM       = del /q /f
CD       = cd /d
LIBS     = "-Wl,--stack,12582912" "-s" "-static"
INCS     = 
CXXINCS  = 
CXXFLAGS = $(CXXINCS) "-fno-ms-extensions" "-O2" "-pipe" "-Werror=return-type" "-Werror=vla"
CFLAGS   = $(INCS) "-fno-ms-extensions" "-O2" "-pipe" "-Werror=implicit-int" "-Werror=return-type" "-Werror=vla"
NASM_FLAGS   =  "-f" "elf64"
WINDRESFLAGS = 
RES      = CITM_a0_private.res
OBJ      = Code/ui.o Code/save.o Code/main.o Code/map.o Code/game.o Code/entity.o $(RES)
BIN      = CITM_a0.8.4_rc1.exe
LINKOBJ  = "Code/ui.o" "Code/save.o" "Code/main.o" "Code/map.o" "Code/game.o" "Code/entity.o" "CITM_a0_private.res"
CLEANOBJ = "Code\ui.o" "Code\save.o" "Code\main.o" "Code\map.o" "Code\game.o" "Code\entity.o" "CITM_a0_private.res" "CITM_a0.8.4_rc1.exe"

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	-$(RM) $(CLEANOBJ) >NUL 2>&1

CITM_a0.8.4_rc1.exe: $(OBJ)

	$(CXX) $(LINKOBJ) -o "CITM_a0.8.4_rc1.exe" $(LIBS)

Code/ui.o: Code/ui.cpp Lib/map.h Lib/save.h Lib/entity.h Lib/ui.h Lib/game.h
	$(CXX) -c "Code/ui.cpp" -o "Code/ui.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

Code/save.o: Code/save.cpp Lib/map.h Lib/save.h Lib/entity.h Lib/ui.h Lib/game.h
	$(CXX) -c "Code/save.cpp" -o "Code/save.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

Code/main.o: Code/main.cpp Lib/map.h Lib/save.h Lib/entity.h Lib/ui.h Lib/game.h
	$(CXX) -c "Code/main.cpp" -o "Code/main.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

Code/map.o: Code/map.cpp Lib/map.h Lib/save.h Lib/entity.h Lib/ui.h Lib/game.h
	$(CXX) -c "Code/map.cpp" -o "Code/map.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

Code/game.o: Code/game.cpp Lib/map.h Lib/save.h Lib/entity.h Lib/ui.h Lib/game.h
	$(CXX) -c "Code/game.cpp" -o "Code/game.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

Code/entity.o: Code/entity.cpp Lib/map.h Lib/save.h Lib/entity.h Lib/ui.h Lib/game.h
	$(CXX) -c "Code/entity.cpp" -o "Code/entity.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

CITM_a0_private.res: CITM_a0_private.rc 
	$(WINDRES) -i "CITM_a0_private.rc" --input-format=rc -o "CITM_a0_private.res" -O coff $(WINDRESFLAGS) 

