# Project: Alpha 0.8.4-Dev-snapshot260502-Project
# Makefile created by Red Panda C++ 3.3.3147

CXX      = "g++.exe"
CC       = "gcc.exe"
WINDRES  = "windres.exe"
RM       = del /q /f
CD       = cd /d
LIBS     = "-Wl,--stack,12582912"
INCS     = 
CXXINCS  = 
CXXFLAGS = $(CXXINCS) "-g3" "-pipe" "-Wall" "-fexec-charset=gbk" "-D_DEBUG"
CFLAGS   = $(INCS) "-g3" "-pipe" "-Wall" "-fexec-charset=gbk" "-D_DEBUG"
WINDRESFLAGS = 
RES      = Alpha_0_private.res
OBJ      = Code/game.o Code/main.o Code/map.o Code/entity.o Code/ui.o $(RES)
BIN      = Alpha\ 0.8.4-Dev-snapshot260502-Project.exe
LINKOBJ  = "Code/game.o" "Code/main.o" "Code/map.o" "Code/entity.o" "Code/ui.o" "Alpha_0_private.res"
CLEANOBJ = "Code\game.o" "Code\main.o" "Code\map.o" "Code\entity.o" "Code\ui.o" "Alpha_0_private.res" "Alpha 0.8.4-Dev-snapshot260502-Project.exe"

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	-$(RM) $(CLEANOBJ) >NUL 2>&1

Alpha\ 0.8.4-Dev-snapshot260502-Project.exe: $(OBJ)

	$(CXX) $(LINKOBJ) -o "Alpha 0.8.4-Dev-snapshot260502-Project.exe" $(LIBS)

Code/game.o: Code/game.cpp Lib/map.h Lib/game.h Lib/ui.h Lib/entity.h
	$(CXX) -c "Code/game.cpp" -o "Code/game.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

Code/main.o: Code/main.cpp Lib/map.h Lib/game.h Lib/ui.h Lib/entity.h
	$(CXX) -c "Code/main.cpp" -o "Code/main.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

Code/map.o: Code/map.cpp Lib/map.h Lib/game.h Lib/ui.h Lib/entity.h
	$(CXX) -c "Code/map.cpp" -o "Code/map.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

Code/entity.o: Code/entity.cpp Lib/map.h Lib/game.h Lib/ui.h Lib/entity.h
	$(CXX) -c "Code/entity.cpp" -o "Code/entity.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

Code/ui.o: Code/ui.cpp Lib/map.h Lib/game.h Lib/ui.h Lib/entity.h
	$(CXX) -c "Code/ui.cpp" -o "Code/ui.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

Alpha_0_private.res: Alpha_0_private.rc 
	$(WINDRES) -i "Alpha_0_private.rc" --input-format=rc -o "Alpha_0_private.res" -O coff $(WINDRESFLAGS) 

