# Project: Project1
# Makefile created by Red Panda C++ 3.3.3147

CXX      = "g++.exe"
CC       = "gcc.exe"
WINDRES  = "windres.exe"
RM       = del /q /f
CD       = cd /d
LIBS     = "-Wl,--stack,12582912"
INCS     = 
CXXINCS  = 
CXXFLAGS = $(CXXINCS) "-g3" "-pipe" "-Wall" "-fexec-charset=gbk" "-D_DEBUG"
CFLAGS   = $(INCS) "-g3" "-pipe" "-Wall" "-fexec-charset=gbk" "-D_DEBUG"
WINDRESFLAGS = 
RES      = Project1_private.res
OBJ      = entity.o map.o ui.o game.o main.o $(RES)
BIN      = Project1.exe
LINKOBJ  = "entity.o" "map.o" "ui.o" "game.o" "main.o" "Project1_private.res"
CLEANOBJ = "entity.o" "map.o" "ui.o" "game.o" "main.o" "Project1_private.res" "Project1.exe"

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	-$(RM) $(CLEANOBJ) >NUL 2>&1

Project1.exe: $(OBJ)

	$(CXX) $(LINKOBJ) -o "Project1.exe" $(LIBS)

entity.o: entity.cpp Lib/ui.h Lib/game.h Lib/entity.h Lib/map.h
	$(CXX) -c "entity.cpp" -o "entity.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

map.o: map.cpp Lib/ui.h Lib/game.h Lib/entity.h Lib/map.h
	$(CXX) -c "map.cpp" -o "map.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

ui.o: ui.cpp Lib/ui.h Lib/game.h Lib/entity.h Lib/map.h
	$(CXX) -c "ui.cpp" -o "ui.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

game.o: game.cpp Lib/ui.h Lib/game.h Lib/entity.h Lib/map.h
	$(CXX) -c "game.cpp" -o "game.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

main.o: main.cpp Lib/ui.h Lib/game.h Lib/entity.h Lib/map.h
	$(CXX) -c "main.cpp" -o "main.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

Project1_private.res: Project1_private.rc 
	$(WINDRES) -i "Project1_private.rc" --input-format=rc -o "Project1_private.res" -O coff $(WINDRESFLAGS) 

